### ISSUE TITLE
Le site ne build pas depuis 8 jours (bientôt 9)

### ISSUE THREAD

**Issue by oncletom** [betagouv/holodeck-dashboard#702]
![image](https://user-images.githubusercontent.com/138627/114748530-5098c380-9d52-11eb-9b09-f3c94ab361cb.png)

```
Run LATEST=$(find ./results/* -type d -prune | tail -n 1)
  LATEST=$(find ./results/* -type d -prune | tail -n 1)
  yarn
  # this create a report.json to build the website
  # also copies html reports to www/public
  node src/report > www/src/report.json
  cd www
  yarn
  CI=false yarn build
  touch build/.nojekyll
  shell: /usr/bin/bash -e {0}
  env:
    SKIP_PREFLIGHT_CHECK: true
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.51s.
e SyntaxError: /home/runner/work/holodeck-dashboard/holodeck-dashboard/results/aHR0cHM6Ly9hdWRpb2NvbmYubnVtZXJpcXVlLmdvdXYuZnI=/20210407_004213/http.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireJson (/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:10:12)
    at /home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:69:17
    at Array.map (<anonymous>)
    at generateReport (/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:55:6)
e Error: Cannot find module '../../results/aHR0cHM6Ly9wbGFjZS1kZXMtZW50cmVwcmlzZXMuYmV0YS5nb3V2LmZy/20210407_014742/lhr.json'
Require stack:
- /home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireJson (/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:10:12)
    at /home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:76:29
    at Array.map (<anonymous>)
    at generateReport (/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:55:6)
    at Object.<anonymous> (/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:104:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js'
  ]
}
/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:35
    const { requestedUrl, finalUrl, categories, audits } = result;
            ^

TypeError: Cannot destructure property 'requestedUrl' of 'result' as it is null.
    at Object.lhr (/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:35:13)
    at /home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:76:25
    at Array.map (<anonymous>)
    at generateReport (/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:55:6)
    at Object.<anonymous> (/home/runner/work/holodeck-dashboard/holodeck-dashboard/src/report/index.js:104:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
Error: Process completed with exit code 1.
```

**Comment by oncletom** [comment]
@jdauphant j'te ping directement parce que je vois environ 900 issues ouvertes automatiquement et je ne suis pas certain que ma demande soit visible dans cette masse !

**Comment by jdauphant** [comment]
Merci pour cette petite aiguille ;) 
il y avait une faute de frappe sur une URL, c'est corrigé maintenant.

On va bientôt passer à la nouvelle version ici : https://github.com/SocialGouv/dashlord
